export const PI_BRIDGE_MODELS = {
	models: [{
		slug: "pi",
		display_name: "Pi",
		description: "Pi coding agent through Codex Mobile",
		base_instructions: "Forward the user's request to the Pi coding agent.",
		default_reasoning_level: "medium",
		supported_reasoning_levels: [
			{ effort: "low", description: "Use Pi's low thinking level" },
			{ effort: "medium", description: "Use Pi's medium thinking level" },
			{ effort: "high", description: "Use Pi's high thinking level" },
		],
		shell_type: "shell_command",
		visibility: "list",
		supported_in_api: true,
		priority: 0,
		upgrade: null,
		model_messages: {
			instructions_template: "Forward the user's request to the Pi coding agent.",
			instructions_variables: null,
			approvals: null,
			collaboration_modes: null,
			auto_review: null,
			permissions: null,
			token_budget: null,
		},
		include_skills_usage_instructions: false,
		include_plugin_usage_instructions: false,
		default_reasoning_summary: "none",
		support_verbosity: false,
		default_verbosity: null,
		apply_patch_tool_type: null,
		web_search_tool_type: "text",
		truncation_policy: { mode: "tokens", limit: 10_000 },
		supports_parallel_tool_calls: false,
		supports_image_detail_original: false,
		context_window: 272_000,
		max_context_window: 272_000,
		effective_context_window_percent: 95,
		experimental_supported_tools: [],
		input_modalities: ["text", "image"],
		supports_search_tool: false,
		use_responses_lite: false,
	}],
};
